name: RPtorch
channels:
  - conda-forge
  - liulab-dfci
  - bioconda
  - pytorch
dependencies:
  - python=3.8
  - pytorch==1.8.0
  - torchvision==0.9.0
  - tqdm
  - numpy==1.20.1
  - scipy==1.6.0
  - joblib==1.0.1
  - lisa2==2.2.4
  - fire
  - pip
  - pip:
    - pyro-ppl==1.5.2